language: node_js
notifications:
  email: false
  slack: lumident:Kkpxv0P1EHFvumqsHHfxKLv2
cache:
  directories:
  - node_modules
  - bower_components
node_js:
  - "4.2"
before_script:
  - sudo apt-get install -y tree
  - bower install
script:
  - gulp build
  - tree build
before_deploy:
    - ls -la
    - pwd
    - cd ./build
deploy:
  provider: heroku
  api_key:
    secure: "26f01ce9-f060-47ec-b7f3-cb1a58438559"
  skip_cleanup: true
  run:
    - cd build