language: node_js
notifications:
  email: false
  slack: lumident:Kkpxv0P1EHFvumqsHHfxKLv2
node_js:
  - "4.2"
before_script:
  - sudo apt-get install -y tree
  - bower i
script:
  - gulp build
  - tree build